# DVC Pipeline for Sematlas Data Processing
# This file defines the complete data processing pipeline from raw data to model-ready datasets

stages:
  download_neurosynth:
    cmd: python scripts/download_neurosynth_simple.py
    deps:
      - scripts/download_neurosynth_simple.py
    outs:
      - data/raw/mock_database.json
      - data/raw/download_metadata.json
    desc: "Download Neurosynth database with coordinate and metadata"
    
  deduplication:
    cmd: python scripts/test_deduplication.py
    deps:
      - data/raw/mock_database.json
      - src/data/deduplication.py
    outs:
      - data/processed/deduplicated_data.csv
      - data/processed/deduplicated_data_deduplication_stats.json
    desc: "Apply directional deduplication to coordinate data"
    
  coordinate_validation:
    cmd: python scripts/apply_coordinate_correction.py
    deps:
      - data/processed/deduplicated_data.csv
      - src/data/coordinate_transform.py
      - scripts/apply_coordinate_correction.py
    outs:
      - data/processed/coordinate_validated_data.csv
      - data/processed/coordinate_validation_log.json
    desc: "Validate Neurosynth coordinates are in expected MNI152 ranges"
    
  create_splits:
    cmd: python scripts/create_data_splits.py
    deps:
      - data/processed/coordinate_validated_data.csv
      - scripts/create_data_splits.py
    outs:
      - data/processed/train_split.csv
      - data/processed/val_split.csv
      - data/processed/test_split.csv
      - data/processed/split_metadata.json
    desc: "Create train/validation/test splits (70/15/15)"
    
  volumetric_cache:
    cmd: python src/data/volumetric_cache_simple.py
    deps:
      - data/processed/coordinate_validated_data.csv
      - src/data/volumetric_cache_simple.py
    outs:
      - data/processed/volumetric_cache
    desc: "Create volumetric cache with dual-kernel augmentation"

# Metrics to track
metrics:
  - data/processed/deduplicated_data_deduplication_stats.json
  - data/processed/coordinate_validation_log.json
  - data/processed/split_metadata.json

# Parameters for reproducibility (would reference params.yaml if it existed)
# params:
#   - params.yaml