model:
  architecture: "resnet_vae"
  latent_dim: 128
  resnet_depth: 10
  group_norm_groups: 8
  input_shape: [91, 109, 91]  # MNI152 standard brain template shape
  dropout: 0.1

training:
  max_epochs: 100
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.01
  beta_schedule: "linear"  # Options: constant, linear, cyclical
  beta_max: 1.0
  beta_warmup_epochs: 10
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4

data:
  train_split: "data/processed/train_split.csv"
  val_split: "data/processed/val_split.csv"
  test_split: "data/processed/test_split.csv"
  volumetric_cache_path: "data/processed/volumetric_cache_lmdb"
  num_workers: 4
  pin_memory: true

wandb:
  project: "generative-brain-atlas"
  entity: null  # Will use default entity
  name: "baseline-resnet-vae"
  tags: ["baseline", "vae", "sprint1", "resnet"]
  notes: "Baseline 3D ResNet VAE for brain activation map generation"
  log_model: "all"  # Options: false, "all", "end"
  save_dir: "wandb_logs"

checkpointing:
  monitor: "val_loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  dirpath: "checkpoints"
  filename: "resnet-vae-{epoch:02d}-{val_loss:.3f}"

early_stopping:
  monitor: "val_loss"
  patience: 15
  mode: "min"
  min_delta: 0.001

logging:
  val_check_interval: 1.0
  log_every_n_steps: 50
  log_images_every_n_epochs: 5
  num_sample_images: 4

hardware:
  accelerator: "auto"  # Will detect GPU/CPU automatically
  precision: "16-mixed"  # Use mixed precision for memory efficiency
  devices: 1
  num_nodes: 1